apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-gke

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client-gke
  template:
    metadata:
      labels:
        app: grpc-client-gke
    spec:
      containers:
      - name: grpc-client-gke
        image: gcr.io/fit-overview-314113/grpc-client-image:latest
        ports:
        - containerPort: 8080
        env: 
        - name: GRPC_ENDPOINT
          value: grpc-server-gke:50051
        
