apiVersion: v1
kind: Service
metadata:
 name: grpc-client-gke
 labels:
   app: grpc-client-gke
spec:
 type: LoadBalancer
 ports:
 - port: 8080
   targetPort: 8080
 selector:
   app: grpc-client-gke