apiVersion: v1
kind: Service
metadata:
 name: grpc-server-gke
 labels:
   app: grpc-server-gke
spec:
 type: LoadBalancer
 ports:
 - port: 50051
   targetPort: 50051
 selector:
   app: grpc-server-gke